### PR TITLE
Dates should be strings not date objects

### PR DESCRIPTION
**Pull request by esqu1**
Ran into this problem while writing the penn-mobile-server endpoint.

### CODE REVIEW

**Comment by adelq** [comment]
Tests are failing, can you check it out?
Also, can't you do the string formatting on penn-mobile-server? I'm slightly leaning towards that unless unfeasible/too much code/too much complexity

**Comment by esqu1** [comment]
Tests are failing in directory_test.

Would it not be more convenient for other project to simply have strings rather than passing datetime objects instead?

**Comment by adelq** [comment]
Well, it depends, but since this is the python SDK, I think people would expect date objects that they can then format into strings. The alternative is returning strings, which then need to be parsed and then reformatted. This looks simple enough that it doesn't matter. LGTM. Can you look into the tests issue?

**Comment by esqu1** [comment]
The tests were flip-flopping as per usual...should be good now.

**Comment by adelq** [comment]
Can you contact Penn OpenData to let them know about this issue?

**Pull request merged**
